// carsData.js
// Seed data for Car schema. Each object matches the schema you provided.
import {
  Ducati, Farari, FarariRed, GTROne, GTRTwo, GrandVitara, GreenCar, KoenigseggOne, KoenigseggTwo, LemboAve
} from '../assets/cars/index'
const carsData = [
  {
    type: "hatchback",
    name: "Wagon R",
    plate: "DL01AB1234",
    model: "ZXI",
    brand: "Maruti Suzuki",
    transmission: "Manual",
    seating: 5,
    fuel: "Petrol",
    price: 3500,
    fuelCapacity: 32,
    mileage: 21,
    description: "A compact hatchback known for fuel efficiency and easy city driving.",
    topSpeed: 150,
    discount: 5,
    imgs: {
      mainImage: Ducati,
      coverImg1: Ducati,
      coverImg2: Ducati,
    },
    isAvailable: true,
    status: "available",
    currentLocation: "Delhi",
    lastServiceDate: new Date("2025-02-15"),
    nextServiceDate: new Date("2025-08-15"),
    maintenanceLogs: [
      { date: new Date("2025-02-15"), note: "General service & oil change", performedBy: "Maruti Service Center - Delhi" }
    ],
    totalBookings: 12
  },
  {
    type: "Luxury SUV",
    name: "G-Wagon",
    plate: "MH12CD5678",
    model: "G63 AMG",
    brand: "Mercedes-Benz",
    transmission: "Automatic",
    seating: 5,
    fuel: "Petrol",
    price: 18000,
    fuelCapacity: 100,
    mileage: 8,
    description: "Iconic luxury off-roader with AMG performance and premium cabin.",
    topSpeed: 210,
    discount: 10,
    imgs: {
      mainImage: Ducati,
      coverImg1: Ducati,
      coverImg2: Ducati,
    },
    isAvailable: true,
    status: "available",
    currentLocation: "Mumbai",
    lastServiceDate: new Date("2025-03-10"),
    nextServiceDate: new Date("2025-09-10"),
    maintenanceLogs: [
      { date: new Date("2025-03-10"), note: "Brake pads replaced", performedBy: "Mercedes Service Center - Mumbai" }
    ],
    totalBookings: 8
  },
  {
    type: "Supercar",
    name: "Huracan Evo",
    plate: "DL09EF2222",
    model: "Evo",
    brand: "Lamborghini",
    transmission: "Automatic",
    seating: 2,
    fuel: "Petrol",
    price: 35000,
    fuelCapacity: 83,
    mileage: 6,
    description: "A high-performance Italian supercar with a V10 engine and track-bred dynamics.",
    topSpeed: 325,
    discount: 0,
    imgs: {
      mainImage: Ducati,
      coverImg1: Ducati,
      coverImg2: Ducati,
    },
    isAvailable: true,
    status: "available",
    currentLocation: "Delhi",
    lastServiceDate: new Date("2025-04-01"),
    nextServiceDate: new Date("2025-10-01"),
    maintenanceLogs: [
      { date: new Date("2025-04-01"), note: "Engine oil & filter, performance check", performedBy: "Lamborghini Service - Delhi" }
    ],
    totalBookings: 4
  },
  {
    type: "Luxury SUV",
    name: "Urus",
    plate: "KA05XY9090",
    model: "Urus V8",
    brand: "Lamborghini",
    transmission: "Automatic",
    seating: 5,
    fuel: "Petrol",
    price: 30000,
    fuelCapacity: 85,
    mileage: 7,
    description: "Super SUV blending Lamborghini performance with usable everyday comfort.",
    topSpeed: 305,
    discount: 0,
    imgs: {
      mainImage: Ducati,
      coverImg1: Ducati,
      coverImg2: Ducati,
    },
    isAvailable: true,
    status: "available",
    currentLocation: "Bangalore",
    lastServiceDate: new Date("2025-03-20"),
    nextServiceDate: new Date("2025-09-20"),
    maintenanceLogs: [
      { date: new Date("2025-03-20"), note: "Tire rotation & balancing", performedBy: "Lamborghini Service - Bangalore" }
    ],
    totalBookings: 6
  },
  {
    type: "SUV",
    name: "Defender",
    plate: "DL11JK6789",
    model: "Defender 110",
    brand: "Land Rover",
    transmission: "Automatic",
    seating: 7,
    fuel: "Diesel",
    price: 15000,
    fuelCapacity: 89,
    mileage: 12,
    description: "Rugged yet refined, great for off-road adventures and family trips.",
    topSpeed: 200,
    discount: 5,
    imgs: {
      mainImage: Ducati,
      coverImg1: Ducati,
      coverImg2: Ducati,
    },
    isAvailable: true,
    status: "available",
    currentLocation: "Delhi",
    lastServiceDate: new Date("2025-04-05"),
    nextServiceDate: new Date("2025-10-05"),
    maintenanceLogs: [
      { date: new Date("2025-04-05"), note: "Full system check and alignment", performedBy: "Land Rover Service - Delhi" }
    ],
    totalBookings: 10
  },
  {
    type: "SUV",
    name: "Tata Safari",
    plate: "MH01TR4321",
    model: "Safari Dark Edition",
    brand: "Tata",
    transmission: "Automatic",
    seating: 7,
    fuel: "Diesel",
    price: 4000,
    fuelCapacity: 50,
    mileage: 15,
    description: "Comfortable 7-seater with strong road presence and solid features.",
    topSpeed: 180,
    discount: 5,
    imgs: {
      mainImage: Ducati,
      coverImg1: Ducati,
      coverImg2: Ducati,
    },
    isAvailable: true,
    status: "available",
    currentLocation: "Mumbai",
    lastServiceDate: new Date("2025-05-01"),
    nextServiceDate: new Date("2025-11-01"),
    maintenanceLogs: [
      { date: new Date("2025-05-01"), note: "Scheduled service & AC check", performedBy: "Tata Service - Mumbai" }
    ],
    totalBookings: 24
  },
  {
    type: "SUV",
    name: "Fortuner",
    plate: "RJ14FT9999",
    model: "Legender",
    brand: "Toyota",
    transmission: "Automatic",
    seating: 7,
    fuel: "Diesel",
    price: 6000,
    fuelCapacity: 80,
    mileage: 14,
    description: "Reliable large SUV ideal for long drives and rough roads.",
    topSpeed: 190,
    discount: 5,
    imgs: {
      mainImage: Ducati,
      coverImg1: Ducati,
      coverImg2: Ducati,
    },
    isAvailable: true,
    status: "available",
    currentLocation: "Jaipur",
    lastServiceDate: new Date("2025-01-20"),
    nextServiceDate: new Date("2025-07-20"),
    maintenanceLogs: [
      { date: new Date("2025-01-20"), note: "Suspension & brake inspection", performedBy: "Toyota Service - Jaipur" }
    ],
    totalBookings: 30
  },
  {
    type: "Off-Road SUV",
    name: "Thar",
    plate: "GJ05TH1234",
    model: "LX",
    brand: "Mahindra",
    transmission: "Manual",
    seating: 4,
    fuel: "Petrol",
    price: 3500,
    fuelCapacity: 57,
    mileage: 14,
    description: "Iconic off-roader with great ground clearance and convertible top options.",
    topSpeed: 160,
    discount: 0,
    imgs: {
      mainImage: Ducati,
      coverImg1: Ducati,
      coverImg2: Ducati,
    },
    isAvailable: true,
    status: "available",
    currentLocation: "Ahmedabad",
    lastServiceDate: new Date("2025-03-05"),
    nextServiceDate: new Date("2025-09-05"),
    maintenanceLogs: [
      { date: new Date("2025-03-05"), note: "4x4 system check and oil service", performedBy: "Mahindra Service - Ahmedabad" }
    ],
    totalBookings: 18
  },
  {
    type: "MUV",
    name: "Ertiga",
    plate: "PB10ER4444",
    model: "ZXI",
    brand: "Maruti Suzuki",
    transmission: "Manual",
    seating: 7,
    fuel: "Petrol",
    price: 2500,
    fuelCapacity: 45,
    mileage: 18,
    description: "Affordable 7-seater family MUV with decent fuel economy.",
    topSpeed: 160,
    discount: 5,
    imgs: {
      mainImage: Ducati,
      coverImg1: Ducati,
      coverImg2: Ducati,
    },
    isAvailable: true,
    status: "available",
    currentLocation: "Chandigarh",
    lastServiceDate: new Date("2025-04-12"),
    nextServiceDate: new Date("2025-10-12"),
    maintenanceLogs: [
      { date: new Date("2025-04-12"), note: "AC service & tyre rotation", performedBy: "Maruti Service - Chandigarh" }
    ],
    totalBookings: 20
  },
  {
    type: "hatchback",
    name: "Swift",
    plate: "UP32SW1111",
    model: "VXI",
    brand: "Maruti Suzuki",
    transmission: "Manual",
    seating: 5,
    fuel: "Petrol",
    price: 1500,
    fuelCapacity: 37,
    mileage: 19,
    description: "Popular hatchback with a sportier design and peppy engine.",
    topSpeed: 165,
    discount: 5,
    imgs: {
      mainImage: Ducati,
      coverImg1: Ducati,
      coverImg2: Ducati,
    },
    isAvailable: true,
    status: "available",
    currentLocation: "Lucknow",
    lastServiceDate: new Date("2025-02-28"),
    nextServiceDate: new Date("2025-08-28"),
    maintenanceLogs: [
      { date: new Date("2025-02-28"), note: "Oil change & brake check", performedBy: "Maruti Service - Lucknow" }
    ],
    totalBookings: 28
  },
  {
    type: "hatchback",
    name: "Celerio",
    plate: "CH01CE2222",
    model: "ZXI",
    brand: "Maruti Suzuki",
    transmission: "Manual",
    seating: 5,
    fuel: "Petrol",
    price: 1100,
    fuelCapacity: 35,
    mileage: 22,
    description: "Economical city hatchback with simple features and great mileage.",
    topSpeed: 145,
    discount: 5,
    imgs: {
      mainImage: Ducati,
      coverImg1: Ducati,
      coverImg2: Ducati,
    },
    isAvailable: true,
    status: "available",
    currentLocation: "Chandigarh",
    lastServiceDate: new Date("2025-03-18"),
    nextServiceDate: new Date("2025-09-18"),
    maintenanceLogs: [
      { date: new Date("2025-03-18"), note: "Minor service and filter change", performedBy: "Maruti Service - Chandigarh" }
    ],
    totalBookings: 9
  },
  // 15 additional cars
  {
    type: "SUV",
    name: "Creta",
    plate: "TN07CR7777",
    model: "SX(O)",
    brand: "Hyundai",
    transmission: "Automatic",
    seating: 5,
    fuel: "Petrol",
    price: 3500,
    fuelCapacity: 50,
    mileage: 16,
    description: "Feature-rich compact SUV with comfortable ride and modern infotainment.",
    topSpeed: 185,
    discount: 5,
    imgs: {
      mainImage: Ducati,
      coverImg1: Ducati,
      coverImg2: Ducati,
    },
    isAvailable: true,
    status: "available",
    currentLocation: "Chennai",
    lastServiceDate: new Date("2025-05-05"),
    nextServiceDate: new Date("2025-11-05"),
    maintenanceLogs: [
      { date: new Date("2025-05-05"), note: "General service & navigation update", performedBy: "Hyundai Service - Chennai" }
    ],
    totalBookings: 22
  },
  {
    type: "SUV",
    name: "Seltos",
    plate: "GJ01SK3333",
    model: "HTX",
    brand: "Kia",
    transmission: "Automatic",
    seating: 5,
    fuel: "Petrol",
    price: 3300,
    fuelCapacity: 50,
    mileage: 15,
    description: "Sporty compact SUV with strong styling and tech features.",
    topSpeed: 190,
    discount: 5,
    imgs: {
      mainImage: Ducati,
      coverImg1: Ducati,
      coverImg2: Ducati,
    },
    isAvailable: true,
    status: "available",
    currentLocation: "Vadodara",
    lastServiceDate: new Date("2025-04-22"),
    nextServiceDate: new Date("2025-10-22"),
    maintenanceLogs: [
      { date: new Date("2025-04-22"), note: "Software update & tyre check", performedBy: "Kia Service - Vadodara" }
    ],
    totalBookings: 16
  },
  {
    type: "Sedan",
    name: "City",
    plate: "AP09CT5555",
    model: "ZX",
    brand: "Honda",
    transmission: "Automatic",
    seating: 5,
    fuel: "Petrol",
    price: 2800,
    fuelCapacity: 47,
    mileage: 17,
    description: "Comfortable sedan with good boot space and refined engine.",
    topSpeed: 190,
    discount: 5,
    imgs: {
      mainImage: Ducati,
      coverImg1: Ducati,
      coverImg2: Ducati,
    },
    isAvailable: true,
    status: "available",
    currentLocation: "Vijayawada",
    lastServiceDate: new Date("2025-03-28"),
    nextServiceDate: new Date("2025-09-28"),
    maintenanceLogs: [
      { date: new Date("2025-03-28"), note: "Air filter & brake check", performedBy: "Honda Service - Vijayawada" }
    ],
    totalBookings: 21
  },
  {
    type: "Sedan",
    name: "Verna",
    plate: "TS07VA1212",
    model: "SX",
    brand: "Hyundai",
    transmission: "Automatic",
    seating: 5,
    fuel: "Petrol",
    price: 2700,
    fuelCapacity: 45,
    mileage: 16,
    description: "Stylish sedan with smooth ride quality and tech features.",
    topSpeed: 185,
    discount: 5,
    imgs: {
      mainImage: Ducati,
      coverImg1: Ducati,
      coverImg2: Ducati,
    },
    isAvailable: true,
    status: "available",
    currentLocation: "Hyderabad",
    lastServiceDate: new Date("2025-02-18"),
    nextServiceDate: new Date("2025-08-18"),
    maintenanceLogs: [
      { date: new Date("2025-02-18"), note: "Suspension inspection", performedBy: "Hyundai Service - Hyderabad" }
    ],
    totalBookings: 14
  },
  {
    type: "hatchback",
    name: "i20",
    plate: "KL07IY9876",
    model: "Asta",
    brand: "Hyundai",
    transmission: "Manual",
    seating: 5,
    fuel: "Petrol",
    price: 1600,
    fuelCapacity: 37,
    mileage: 18,
    description: "Premium hatchback with upmarket features and good driving dynamics.",
    topSpeed: 175,
    discount: 5,
    imgs: {
      mainImage: Ducati,
      coverImg1: Ducati,
      coverImg2: Ducati,
    },
    isAvailable: true,
    status: "available",
    currentLocation: "Kochi",
    lastServiceDate: new Date("2025-05-12"),
    nextServiceDate: new Date("2025-11-12"),
    maintenanceLogs: [
      { date: new Date("2025-05-12"), note: "Infotainment update & basic service", performedBy: "Hyundai Service - Kochi" }
    ],
    totalBookings: 11
  },
  {
    type: "SUV",
    name: "XUV700",
    plate: "UP78XV2468",
    model: "AX7",
    brand: "Mahindra",
    transmission: "Automatic",
    seating: 7,
    fuel: "Petrol",
    price: 5000,
    fuelCapacity: 60,
    mileage: 14,
    description: "Feature-loaded 7-seater with strong performance and safety tech.",
    topSpeed: 190,
    discount: 5,
    imgs: {
      mainImage: Ducati,
      coverImg1: Ducati,
      coverImg2: Ducati,
    },
    isAvailable: true,
    status: "available",
    currentLocation: "Kanpur",
    lastServiceDate: new Date("2025-04-02"),
    nextServiceDate: new Date("2025-10-02"),
    maintenanceLogs: [
      { date: new Date("2025-04-02"), note: "ADAS calibration & general service", performedBy: "Mahindra Service - Kanpur" }
    ],
    totalBookings: 19
  },
  {
    type: "SUV",
    name: "Harrier",
    plate: "GJ05HR5555",
    model: "Creative",
    brand: "Tata",
    transmission: "Automatic",
    seating: 5,
    fuel: "Diesel",
    price: 4200,
    fuelCapacity: 55,
    mileage: 15,
    description: "Solidly built SUV with refined ride and premium cabin touches.",
    topSpeed: 185,
    discount: 5,
    imgs: {
      mainImage: Ducati,
      coverImg1: Ducati,
      coverImg2: Ducati,
    },
    isAvailable: true,
    status: "available",
    currentLocation: "Surat",
    lastServiceDate: new Date("2025-03-30"),
    nextServiceDate: new Date("2025-09-30"),
    maintenanceLogs: [
      { date: new Date("2025-03-30"), note: "Engine check & software update", performedBy: "Tata Service - Surat" }
    ],
    totalBookings: 13
  },
  {
    type: "Electric Sedan",
    name: "Model 3",
    plate: "MH20TM0001",
    model: "Long Range",
    brand: "Tesla",
    transmission: "Automatic",
    seating: 5,
    fuel: "Electric",
    price: 8000,
    fuelCapacity: 0,
    mileage: 450,
    description: "Electric sedan with long range and Autopilot features (mileage in km / full charge).",
    topSpeed: 233,
    discount: 0,
    imgs: {
      mainImage: Ducati,
      coverImg1: Ducati,
      coverImg2: Ducati,
    },
    isAvailable: true,
    status: "available",
    currentLocation: "Pune",
    lastServiceDate: new Date("2025-06-01"),
    nextServiceDate: new Date("2025-12-01"),
    maintenanceLogs: [
      { date: new Date("2025-06-01"), note: "Battery health check & software update", performedBy: "Tesla Service - Pune" }
    ],
    totalBookings: 7
  },
  {
    type: "SUV",
    name: "Kushaq",
    plate: "MH14KS7878",
    model: "Style",
    brand: "Skoda",
    transmission: "Manual",
    seating: 5,
    fuel: "Petrol",
    price: 3200,
    fuelCapacity: 55,
    mileage: 16,
    description: "European compact SUV with a balanced chassis and premium features.",
    topSpeed: 195,
    discount: 5,
    imgs: {
      mainImage: Ducati,
      coverImg1: Ducati,
      coverImg2: Ducati,
    },
    isAvailable: true,
    status: "available",
    currentLocation: "Nashik",
    lastServiceDate: new Date("2025-05-18"),
    nextServiceDate: new Date("2025-11-18"),
    maintenanceLogs: [
      { date: new Date("2025-05-18"), note: "Wheel alignment & oil change", performedBy: "Skoda Service - Nashik" }
    ],
    totalBookings: 10
  },
  {
    type: "SUV",
    name: "Compass",
    plate: "PB65CP2468",
    model: "Limited",
    brand: "Jeep",
    transmission: "Automatic",
    seating: 5,
    fuel: "Diesel",
    price: 4500,
    fuelCapacity: 60,
    mileage: 13,
    description: "Premium compact SUV with off-road capability and comfortable ride.",
    topSpeed: 190,
    discount: 5,
    imgs: {
      mainImage: Ducati,
      coverImg1: Ducati,
      coverImg2: Ducati,
    },
    isAvailable: true,
    status: "available",
    currentLocation: "Amritsar",
    lastServiceDate: new Date("2025-04-10"),
    nextServiceDate: new Date("2025-10-10"),
    maintenanceLogs: [
      { date: new Date("2025-04-10"), note: "4x4 system check & software update", performedBy: "Jeep Service - Amritsar" }
    ],
    totalBookings: 15
  },
  {
    type: "Sedan",
    name: "Civic",
    plate: "DL04CV7777",
    model: "ZX",
    brand: "Honda",
    transmission: "Automatic",
    seating: 5,
    fuel: "Petrol",
    price: 3000,
    fuelCapacity: 47,
    mileage: 16,
    description: "Premium compact sedan with sporty handling and comfortable cabin.",
    topSpeed: 205,
    discount: 5,
    imgs: {
      mainImage: Ducati,
      coverImg1: Ducati,
      coverImg2: Ducati,
    },
    isAvailable: true,
    status: "available",
    currentLocation: "Delhi",
    lastServiceDate: new Date("2025-03-12"),
    nextServiceDate: new Date("2025-09-12"),
    maintenanceLogs: [
      { date: new Date("2025-03-12"), note: "Full service & AC check", performedBy: "Honda Service - Delhi" }
    ],
    totalBookings: 17
  },
  {
    type: "Luxury Sedan",
    name: "E-Class",
    plate: "MH02EC1212",
    model: "E200",
    brand: "Mercedes-Benz",
    transmission: "Automatic",
    seating: 5,
    fuel: "Petrol",
    price: 12000,
    fuelCapacity: 66,
    mileage: 10,
    description: "Executive luxury sedan with premium comfort and advanced features.",
    topSpeed: 240,
    discount: 10,
    imgs: {
      mainImage: Ducati,
      coverImg1: Ducati,
      coverImg2: Ducati,
    },
    isAvailable: true,
    status: "available",
    currentLocation: "Mumbai",
    lastServiceDate: new Date("2025-02-01"),
    nextServiceDate: new Date("2025-08-01"),
    maintenanceLogs: [
      { date: new Date("2025-02-01"), note: "Interior detail & software update", performedBy: "Mercedes Service - Mumbai" }
    ],
    totalBookings: 9
  },
  {
    type: "Luxury Sedan",
    name: "BMW 7 Series",
    plate: "DL06BM9999",
    model: "730Li",
    brand: "BMW",
    transmission: "Automatic",
    seating: 5,
    fuel: "Petrol",
    price: 20000,
    fuelCapacity: 78,
    mileage: 9,
    description: "Flagship luxury sedan with executive features and limousine comfort.",
    topSpeed: 250,
    discount: 10,
    imgs: {
      mainImage: Ducati,
      coverImg1: Ducati,
      coverImg2: Ducati,
    },
    isAvailable: true,
    status: "available",
    currentLocation: "Delhi",
    lastServiceDate: new Date("2025-01-10"),
    nextServiceDate: new Date("2025-07-10"),
    maintenanceLogs: [
      { date: new Date("2025-01-10"), note: "Engine check & massage seats calibration", performedBy: "BMW Service - Delhi" }
    ],
    totalBookings: 5
  },
  {
    type: "SUV",
    name: "Scorpio-N",
    plate: "RJ27SC3333",
    model: "Z8",
    brand: "Mahindra",
    transmission: "Manual",
    seating: 7,
    fuel: "Diesel",
    price: 4000,
    fuelCapacity: 57,
    mileage: 13,
    description: "Rugged seven-seater with strong torque and a commanding drive position.",
    topSpeed: 175,
    discount: 5,
    imgs: {
      mainImage: Ducati,
      coverImg1: Ducati,
      coverImg2: Ducati,
    },
    isAvailable: true,
    status: "available",
    currentLocation: "Jodhpur",
    lastServiceDate: new Date("2025-02-28"),
    nextServiceDate: new Date("2025-08-28"),
    maintenanceLogs: [
      { date: new Date("2025-02-28"), note: "Clutch & gearbox inspection", performedBy: "Mahindra Service - Jodhpur" }
    ],
    totalBookings: 14
  },
  {
    type: "Compact SUV",
    name: "Venue",
    plate: "KL11VN4444",
    model: "SX Plus",
    brand: "Hyundai",
    transmission: "Manual",
    seating: 5,
    fuel: "Petrol",
    price: 2500,
    fuelCapacity: 37,
    mileage: 18,
    description: "City-friendly compact SUV with connected tech and agile handling.",
    topSpeed: 170,
    discount: 5,
    imgs: {
      mainImage: Ducati,
      coverImg1: Ducati,
      coverImg2: Ducati,
    },
    isAvailable: true,
    status: "available",
    currentLocation: "Thiruvananthapuram",
    lastServiceDate: new Date("2025-05-25"),
    nextServiceDate: new Date("2025-11-25"),
    maintenanceLogs: [
      { date: new Date("2025-05-25"), note: "General service and infotainment check", performedBy: "Hyundai Service - Trivandrum" }
    ],
    totalBookings: 12
  }
];

export default carsData;
